import { CharacterTypeEnum } from "../enums/CharacterTypeEnum"
import type { ICharacter } from "../interfaces/ICharacter"

export const Characters = (): ICharacter[] => {
    return [
        {
            id: "1",
            name: "Clark Kent",
            slug: "clark-kent",
            alias: "Superman",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "DC",
            characterType: CharacterTypeEnum.Hero,
            team: "Justice League",
            description: "The Last Son of Krypton, protector of Earth and symbol of hope for all humanity.",
            strength: 100,
            intelligence: 80,
            speed: 90,
            durability: 100,
            powers: ["Super Strength", "Flight"],
            firstAppearance: "1938"
        } as ICharacter,
        {
            id: "2",
            name: "Bruce Wayne",
            slug: "bruce-wayne",
            alias: "Batman",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "DC",
            characterType: CharacterTypeEnum.Hero,
            team: "Justice League",
            description: "The Dark Knight of Gotham City, using fear as a weapon against crime and corruption.",
            strength: 60,
            intelligence: 100,
            speed: 60,
            durability: 70,
            powers: ["Martial Arts", "Detective Skills"],
            firstAppearance: "1939"
        } as ICharacter,
        {
            id: "3",
            name: "Diana Prince",
            slug: "diana-prince",
            alias: "Mujer Maravilla",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "DC",
            characterType: CharacterTypeEnum.Hero,
            team: "Justice League",
            description: "Amazonian princess and warrior, champion of truth, justice, and equality.",
            strength: 90,
            intelligence: 80,
            speed: 80,
            durability: 90,
            powers: ["Super Strength", "Flight"],
            firstAppearance: "1941"
        } as ICharacter,
        {
            id: "5",
            name: "Peter Parker",
            slug: "peter-parker",
            alias: "Spider-Man",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "Marvel",
            characterType: CharacterTypeEnum.Villain,
            team: "Avengers",
            description: "Your friendly neighborhood Spider-Man, with great power comes great responsibility.",
            strength: 70,
            intelligence: 90,
            speed: 70,
            durability: 70,
            powers: ["Wall Crawling", "Spider Sense"],
            firstAppearance: "1962"
        } as ICharacter,
        {
            id: "6",
            name: "Tony Stark",
            slug: "tony-stark",
            alias: "Iron Man",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "Marvel",
            characterType: CharacterTypeEnum.Hero,
            team: "Avengers",
            description: "Billionaire genius inventor who uses his technology to protect the world.",
            strength: 80,
            intelligence: 100,
            speed: 70,
            durability: 80,
            powers: ["Powered Armor", "Genius Intellect"],
            firstAppearance: "1963"
        } as ICharacter,
        {
            alias: "Deadpool",
            name: "Wade Wilson",
            isActive: true,
            imgPath: "/placeholder.svg?height=300&width=300",
            universe: "Marvel",
            characterType: CharacterTypeEnum.Anti_Hero,
            team: "X-Force",
            description: "The Merc with a Mouth, an unpredictable anti-hero with accelerated healing powers.",
            strength: 60,
            intelligence: 70,
            speed: 70,
            durability: 90,
            powers: ["Healing Factor", "Martial Arts"],
            firstAppearance: "1991"
        } as ICharacter
    ]
}